Repository InterruptorPt/ate-onde-chega-cultura, pull requests merged in 2020-10, with the labels that each got.

#3 bibliotecas.html no readme
  README.md
Labels: enhancement

#34 experiencias jekyll
  _config.yml
Labels: enhancement, hacktoberfest

#37 mapa no read me e pasta de screenshots
  README.md
  assets/screenshots/screenshot-1.png
Labels: documentation, hacktoberfest

#61 keep external libs local
  dist/leaflet/images/layers-2x.png
  dist/leaflet/images/layers.png
  dist/leaflet/images/marker-icon-2x.png
  dist/leaflet/images/marker-icon.png
  dist/leaflet/images/marker-shadow.png
  dist/leaflet/leaflet-src.esm.js
  dist/leaflet/leaflet-src.esm.js.map
  dist/leaflet/leaflet-src.js
  dist/leaflet/leaflet-src.js.map
  dist/leaflet/leaflet.css
  dist/leaflet/leaflet.js
  dist/leaflet/leaflet.js.map
  example-iframe-from-wikidata.html
  mapa.html
  scripts/build_snap.sh
Labels: enhancement, html
